### ISSUE TITLE
Support CAS attributes for CAS 3.0

### ISSUE THREAD

**Issue by ldenoix** [Alexandre-T/casguard#3]
Is it possible to add configuration to retrieve CAS attributes, available in CAS 3.0 and + ?
For exemple, in cas_guard.yaml:
```
cas_guard:
    ...
    attributes:
        # Name of Session attribute
        name: _cas_attr
        #list of attribute, or all attributes 
        list: [uid, mail]
     ...

```
And in CasAuthenticator

```
    public function getCredentials(Request $request)
    {
     ...
       // Return User
        if (phpCAS::getUser()) {
            $request->getSession()->set("CasAttr",phpCAS::getAttributes());
            return phpCAS::getUser();
        }
     ...
     }
```

It sure needs more work than these 2 updates, but you get the idea...
Thanks to tell us if you consider adding this feature.
